### ISSUE TITLE
MongoDB connection disruption

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-uploader#32]
MongoDB connection for oam-uploader periodically disconnects and node service needs to be restarted to fix. Unsure of the specific problem at the moment but flagging for further investigation. Below is the log dump by @dodobas. 

One initial thought is that it looks like we may be running on a Sandbox MongoLab instance. This may be a problem. 

```
151024/180402.320, [error], message: topology was destroyed stack: MongoError: topology was destroyed
    at Server.insert (/local/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:920:49)
    at Server.insert (/local/node_modules/mongodb/lib/server.js:324:17)
    at executeCommands (/local/node_modules/mongodb/lib/bulk/ordered.js:450:23)
    at OrderedBulkOperation.execute (/local/node_modules/mongodb/lib/bulk/ordered.js:503:10)
    at bulkWrite (/local/node_modules/mongodb/lib/collection.js:569:8)
    at Collection.insertMany (/local/node_modules/mongodb/lib/collection.js:471:44)
    at wrapped [as insertMany] (/local/node_modules/newrelic/lib/instrumentation/mongodb.js:185:25)
    at Collection.insert (/local/node_modules/mongodb/lib/collection.js:722:15)
    at wrapped (/local/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at wrappedQuery (/local/node_modules/newrelic/lib/instrumentation/mongodb.js:218:53)
151024/180402.320, [response], http://0.0.0.0:8080: post /tokens {} 500 (4ms)
```

cc @anandthakker @kamicut

**Comment by smit1678** [comment]
Rookie mistake. Posted in wrong repo. Moved here: https://github.com/hotosm/oam-uploader-api/issues/29
